images/agent/pkg/controller/block_device.go

This update introduces a fix in the discovery process of MD RAID block devices. Previously, MD RAID block devices were not detected correctly by our controller. The fix changes the identification method from using serial numbers to using UUIDs, which ensures accurate detection and identification of these devices.
This fix addresses the issue where MD RAID block devices were not being identified by our controller. This was a significant problem as it prevented the correct recognition and management of these devices. By switching to UUIDs for identification, we now have a reliable method for detecting MD RAID block devices, resolving the previous oversight.
After applying this update, MD RAID block devices should now be correctly identified and listed within the system.

[controller] Fix MD RAID block device discovery by reading UUID instead of serial

---

images/agent/pkg/controller/block_device.go
images/agent/pkg/controller/block_device_test.go

This PR removes a previous partUUID fix because it unintentionally broke the naming logic for block devices of type 'part'.
To improve testing and ensure accurate naming, we refactored the code to introduce a specific name generation function and added a test for this functionality.
This PR corrects a bug introduced by a previous update that disrupted the correct naming of devices. By removing the problematic fix and adding a new test, it ensures that device names are generated correctly in the future, preventing confusion or errors in device identification.
The expected result is that the proper mechanism for naming devices will be back in place, making sure every device is named correctly. The added test will help minimize the chance of any future issues, ensuring a more dependable …

[controller] Fix naming bug by removing previous partUUID fix. Refactor name generation. Add test for device name.

---

crds/lvmlogicalvolume.yaml
images/agent/cmd/bc/main.go
images/agent/config/config.go
images/agent/internal/const.go
images/agent/pkg/controller/lvm_logical_volume_watcher.go
images/agent/pkg/controller/lvm_logical_volume_watcher_test.go
images/agent/pkg/controller/lvm_volume_group_discover.go
images/agent/pkg/controller/lvm_volume_group_discover_test.go
images/agent/pkg/controller/lvm_volume_group_watcher.go
images/agent/pkg/controller/lvm_volume_group_watcher_func.go
images/agent/pkg/utils/commands.go
templates/agent/daemonset.yaml

Signed-off-by: viktor.kramarenko <viktor.kramarenko@flant.com>

[controller] Add a LVMLogicalVolumeWatcher controller

---

images/agent/pkg/controller/lvm_logical_volume_watcher.go

[controller] add func AreSizesEqualWithinDelta

---

images/agent/pkg/controller/lvm_logical_volume_watcher.go
images/agent/pkg/controller/lvm_volume_group_watcher.go
images/agent/pkg/controller/lvm_volume_group_watcher_func.go
images/agent/pkg/utils/units.go

This PR addresses an issue where the controller would erroneously enter the resize code path for thin pools even when resizing was not required. This unintended behavior led to errors in the resize logic, preventing the controller from proceeding to handle subsequent thin pools. As a result, the creation of new thin pools was inadvertently blocked. The fix ensures that the controller correctly bypasses the resize logic when no resizing is necessary, allowing for the seamless processing of thin pools and the unimpeded creation of new ones.
This fix is crucial to address a flaw where the controller unnecessarily attempts to resize thin pools, leading to errors and halting further thin pool processing. This issue directly impedes the creation of new thin pools, disrupting normal storage …

[controller] Fix resize for thinPools

---

images/agent/pkg/controller/lvm_logical_volume_watcher_test.go

Signed-off-by: Viktor Kramarenko <viktor.kramarenko@flant.com>
Added tests to the LVMLogicalVolume controller.
To prevent unexpected the controller's behavior.
All tests pass.

[controller] Add tests to LvmLogicalVolumeWatcher controller.

---

templates/agent/daemonset.yaml

Add node affinity to match all our SDS modules
Now nodeSelector match old sds-drbd module label, this PR fix it
Correct DaemonSet scheduling

[controller] Add node affinity

---

crds/lvmlogicalvolume.yaml
images/agent/api/v1alpha1/lvm_logical_volume.go
images/agent/cmd/bc/main.go
images/agent/pkg/controller/lvm_logical_volume_watcher.go
images/agent/pkg/controller/lvm_logical_volume_watcher_test.go
images/agent/pkg/controller/lvm_volume_group_discover.go
images/agent/pkg/utils/commands.go

This PR introduces several improvements to controller managing `LVMLogicalVolume`. Key enhancements include field organization, improved logging mechanisms, and an update in how `actualSize` is displayed to present a human-readable format. Additionally, the update function's event processing in the watcher has been refined to trigger only upon changes in the `LVMLogicalVolume` spec. The method for checking the actual size of LVs on nodes has also been optimized to query specific LVs rather than all LVs on the node, increasing efficiency and accuracy. Furthermore, LV search functionality now accounts for Volume Groups (VGs), ensuring more precise operations.
These changes streamline controller operations and enhance user and system interaction by:
- Improving the clarity and usefulness of …

[controller] Enhance LVMLogicalVolume handling: logging, size display, and event processing

---

.werf/bundle.yaml
images/sds-utils-installer/Dockerfile
images/sds-utils-installer/bin-copier.go
images/sds-utils-installer/go.mod
images/sds-utils-installer/go.sum

Rewrite the bin-copier script in Golang.
Abandon the former shell script.
Independent of the system shell and utilities - eliminates the need for having rsync or explicitly using bash.
An environment-independent binary.

[ci] Rewrite the bin-copier script in Golang.

---

images/agent/Dockerfile
images/agent/pkg/utils/commands.go
images/sds-utils-installer/Dockerfile
templates/agent/daemonset.yaml

In this update, we've changed our approach by moving the `lsblk` binary and its dependent libraries from the host into the container agent image itself. Previously, we deployed our own version of `lsblk` along with necessary libraries onto the host to ensure compatibility. However, executing `lsblk` via `nsenter` directly from the host led to unstable behavior in certain operating systems, such as Ubuntu 20.04, where we encountered `segmentation fault` errors likely due to library incompatibilities. By integrating `lsblk` and its libraries directly into the agent's container image, we eliminate these compatibility issues, aiming for uniform execution across all environments.
The relocation of `lsblk` into the agent's container directly addresses the issue of unstable performance and …

[controller] Move lsblk and its libraries inside the agent image

---

crds/blockdevices.yaml
crds/lvmlogicalvolume.yaml
crds/lvmvolumegroup.yaml

Add age field for custom resource definitions.
Provides more detailed output of lvmLogicalVolume, lvmVolumeGroup, BlockDevices resources.
Age field present in i.e. kubectl get { lvg | llv | bd }

[controller] Add age field

---

images/agent/pkg/controller/lvm_volume_group_discover.go
images/agent/pkg/utils/commands.go

This PR introduces a new function, `filterStdErr`, designed to process stderr output from LVM command executions and filter out specific messages that can be safely ignored. The primary focus is on excluding "Regex version mismatch" messages that arise due to SELinux checks on a statically compiled LVM binary. These messages, while reporting a discrepancy between the regex library versions, do not affect LVM's functionality or compromise system security, as our LVM binary operates independently of system libraries at runtime.
In systems with SELinux, executing LVM commands from our binary generates "Regex version mismatch" warnings in stderr, even when the commands complete successfully. Our controller's logic, which checks for any stderr output to determine operational status, may …

[controller] Implement stderr filtering for LVM commands

---

images/agent/pkg/controller/lvm_logical_volume_bench_test.go

Signed-off-by: Viktor Kramarenko <viktor.kramarenko@flant.com>
A few bench-tests for LVMLogicalVolume controller.
To test LVMLogicalVolume controller stable work.
All tests pass.

[controller] Add bench-tests for LVMLogicalVolume controller

---

images/agent/api/v1alpha1/block_device.go
images/agent/api/v1alpha1/lvm_volume_group.go
images/agent/go.mod
images/agent/internal/type.go
images/agent/pkg/controller/block_device.go
images/agent/pkg/controller/block_device_test.go
images/agent/pkg/controller/controller_reconcile_test.go
images/agent/pkg/controller/lvm_logical_volume_watcher.go
images/agent/pkg/controller/lvm_logical_volume_watcher_test.go
images/agent/pkg/controller/lvm_volume_group_discover.go
images/agent/pkg/controller/lvm_volume_group_discover_test.go
images/agent/pkg/controller/lvm_volume_group_test.go
images/agent/pkg/controller/lvm_volume_group_watcher.go
images/agent/pkg/controller/lvm_volume_group_watcher_func.go
images/agent/pkg/controller/lvm_volume_group_watcher_test.go

Refactoring due to size field type changes from string to quantity.
Less parsing and more accurate code.
No type string for any size field of any resource.

[controller] Change size type from string to quantity

---

images/agent/cmd/main.go
images/agent/config/config.go
images/agent/go.mod
images/agent/go.sum
images/agent/pkg/cache/cache.go
images/agent/pkg/cache/cache_test.go
images/agent/pkg/controller/lvm_volume_group_discover.go
images/agent/pkg/controller/scanner.go
images/agent/pkg/logger/logger.go
images/agent/pkg/throttler/throttler.go
images/agent/pkg/utils/commands.go
templates/agent/daemonset.yaml

Add a scanner for block devices information such as devices, pvs, vgs, lvs, which triggers only if there is any actual event happens on a node. 
It uses a special socket to listen to any block event (new device occurs, pv, vg or lv was created or updated and etc.) on a node and as the event occurs, the scanner scans actual needed information for the sds-node-configurator controller to store it in a cache. 
This logic prevents regular and useless utils commands execution, so a node will got less load.
Any block devices action turns into an event which triggers the scanner to fill its cache with actual information for the controller.

[controller] Add a sds scaner and a cache

---

images/agent/cmd/main.go
images/agent/pkg/cache/cache.go
images/agent/pkg/controller/block_device.go
images/agent/pkg/controller/scanner.go

BlockDevice controller uses cache to get all needed information to create BlockDevice resources successfully.
As the cache was invented to prevent regular and useless utils command executions, the controller should use it.
New BlockDevice resources are creating successfully, old ones are not deleted or updated for no reason.

[controller] Change BlockDevices logic to work with the controller's cache

---

images/agent/cmd/main.go
images/agent/pkg/cache/cache.go
images/agent/pkg/cache/cache_test.go
images/agent/pkg/controller/block_device.go
images/agent/pkg/controller/lvm_volume_group_discover.go
images/agent/pkg/controller/scanner.go
images/agent/pkg/utils/commands.go

LVMVolumeGroupDiscover controller uses cache to get all needed information to create LVMVolumeGroup resources successfully.
As the cache was invented to prevent regular and useless utils command executions, the controller should use it.
New LVMVolumeGroup resources are creating successfully, old one are not deleted or updated for no reason.

[controller] Change LVMVolumeGroupDiscover controller logic to work with the controller's cache

---

images/agent/README.md
images/agent/cmd/main.go
images/agent/config/config.go
images/agent/config/config_test.go

Change metric ports
Now metric ports conflicts with Deckhouse pod
No port conflict in cluster

[monitoring] Change metric ports

---

docs/README.md
docs/README_RU.md

Change the module status from `experimental` to `preview`.
The status of the module in the documentation is `preview`.

[docs] Change the module status to preview

---

images/agent/internal/const.go
images/agent/pkg/controller/block_device.go
images/agent/pkg/controller/lvm_volume_group_discover.go
images/agent/pkg/controller/lvm_volume_group_watcher.go
images/agent/pkg/controller/lvm_volume_group_watcher_func.go
images/sds-health-watcher-controller/internal/const.go
images/sds-health-watcher-controller/pkg/controller/lvg_conditions_watcher.go
images/sds-health-watcher-controller/pkg/controller/sds_infra_watcher_funcs.go

Fixed a Thin-pool requested size validation for existing LVMVolumeGroups with thin pools and no VG free space.
Fixed NotReady condition and phase of a LVMVolumeGroup resource with failed validation. 
Also fixed reconciliation with issue when LVMVolumeGroupDiscover controller got not actual BlockDevice resource due to a kubernetes controller didn't have time to update its cache. This lead to LVMVolumeGroup resource got stuck into NotReady state, although the VG was actually created and BlockDevice resources contain the required information.
It fixes unexpected behavior when existing LVMVolumeGroup with Thin-pool and no VG free space left turns to NotReady with failed validation (as there was no free VG space at all). 
Failed validation for new configuration (i.e. resource's update) turns …

[controller] Fix thin-pool requested size validation and NotReady status

---

crds/doc-ru-lvmvolumegroup.yaml
crds/lvmlogicalvolume.yaml
crds/lvmvolumegroup.yaml
images/agent/api/v1alpha1/lvm_volume_group.go
images/agent/internal/type.go
images/agent/pkg/controller/lvm_logical_volume_watcher.go
images/agent/pkg/controller/lvm_logical_volume_watcher_func.go
images/agent/pkg/controller/lvm_logical_volume_watcher_test.go
images/agent/pkg/controller/lvm_volume_group_discover.go
images/agent/pkg/controller/lvm_volume_group_discover_test.go
images/agent/pkg/controller/lvm_volume_group_watcher_func.go
images/sds-health-watcher-controller/api/v1alpha1/lvm_volume_group.go
images/sds-health-watcher-controller/pkg/controller/lvg_status_watcher.go

Add VG FreeVG and Thin pool AvailableSpace fields, to store free spaces of VG and Thin pool in LVMVolumeGroup resources.
Notice, that AvailableSpace field is counted dynamically according to AllocationLimit field's value.
These fields allow the different controllers to get needed information straight from the resource, and do not count it by themselves from different places.
Also, those fields might be helpful to users and UI to show the VG and Thin Pool free spaces.
Users might see VGFree in the LVMVolumeGroup's Status and AvailableSpace in the LVMVolumeGroup Thin-pool Status.
AvailableSpace field is counted dynamically according to AllocationLimit field's value.

[controller] Added free space field to LVMVolumeGroup VG and ThinPools

---

images/agent/pkg/controller/block_device.go
images/agent/pkg/controller/lvm_logical_volume_watcher.go
images/agent/pkg/controller/lvm_volume_group_discover.go
images/agent/pkg/controller/lvm_volume_group_watcher.go
images/agent/pkg/controller/lvm_volume_group_watcher_constants.go
images/agent/pkg/controller/lvm_volume_group_watcher_func.go

LVMVolumeGroupDiscover controller no longer deletes the resources if corresponding VG on the node was deleted. Now it turns the resource Ready state to False as VGReady condition turned false due to missed VG. 
LVMVolumeGroupWatcher controller deletes a resource, if a user annotate the resource with delete-annotation.
Users don't miss LVMVolumeGroup resource if corresponding VG was deleted, but can see if the resource turned to Ready false state. This behaviour prevents automatic VG creation with generated name (if VG was recreated on the node), so the work-flow becomes more reasonable and clear for the users.  
Created LVMVolumeGroup resources got no deleted if corresponding VG was deleted on the node, but their Ready phases got False. 
If a user recreates VG on the node with special tag …

[controller] Move LVMVolumeGroup resource deletion logic from Discover to Watcher

---

images/agent/pkg/controller/lvm_volume_group_watcher_func.go

Fixed a bug in which a block device extension doesn't result in auto PV extension.
PV and VG did not got extended if an included block device was extended.
If a user extends a block device on the node, a PV and VG will be auto extended as well.

[controller] Fix a block device extension

---

images/agent/README.md
images/agent/config/config.go
images/agent/config/config_test.go
images/sds-health-watcher-controller/config/config.go
images/sds-health-watcher-controller/config/config_test.go
templates/agent/daemonset.yaml
templates/agent/podmonitor.yaml
templates/sds-health-watcher-controller/deployment.yaml
templates/sds-health-watcher-controller/servicemonitor.yaml

Add metric collector for sds-node-configurator agent
We need metrics for node-configurator monitoring
Node configurator metrics collector

[monitoring] Add metrics collectors

---

.github/workflows/trivy_check.yaml
images/agent/werf.inc.yaml
images/sds-utils-installer/werf.inc.yaml

Add Trivy vulnerables check (also fixes one vulnerable in go code)
Modules without known vulnerables

[CI] Add Trivy vulnerables check

---

images/agent/src/go.mod
images/agent/src/go.sum
images/agent/src/internal/const.go
images/agent/src/pkg/controller/block_device.go
images/agent/src/pkg/controller/block_device_test.go
images/agent/src/pkg/controller/controller_reconcile_test.go

As some of BlockDevice status values might have spaces within themselves, and the CR labels do not support spaces, we have to replace them with "-" sign with slug pkg.
Because of the bug some of BlockDevice resources are not able to be created.
Any BlockDevice resource might be created.

[controller] Fix a bug with labels containing spaces.

---

images/agent/src/pkg/controller/lvm_volume_group_discover.go
images/sds-health-watcher-controller/src/pkg/controller/sds_infra_watcher.go
images/sds-health-watcher-controller/src/pkg/controller/sds_infra_watcher_funcs.go
images/sds-health-watcher-controller/src/pkg/controller/sds_infra_watcher_test.go

Fixed the way the controller count the nodes used by LVMVolumeGroup resources
It prevents the case when the controller gets some nodes without a LVMVolumeGroup resource, but still used to count as there should be a sds-node-configurator pod on the node.
The controller operates only with LVMVolumeGroup used nodes.

[controller] Fix sds-health-watcher controller's incorrect used nodes count 

---

.github/workflows/build_dev.yml
.github/workflows/trivy_image_check.yaml
templates/agent/bashible-filter-loop-devices.yaml
templates/agent/nodegroupconfiguration-blacklist-loop-devices.yaml

Blacklist (filter out) 'loop' devices from LVM and Multipath utilities (like pvscan, lvscan, etc)
We have LVM devices in VMs (KubeVirt) and we do not want the contents of these devices (in the VMs) to be scanned by the physical host.
Add `global_filter="r|^/dev/loop[0-9]+|"` in `/etc/lvm/lvm.conf` on each node.
Also add `/etc/multipath/conf.d/loop-blacklist.conf` with blacklist-filter for multipath.

[controller] Filter loop devices

---

hooks/convert_bd_names_to_selector.py

Fixed the error of migration_script, if some LVMVolumeGroup resource does not have any label.
If a LVMVolumeGroup resource does not have any label, the migration script results into error every time and blocks sds-node-configurator deploying process.
Even if a LVMVolumeGroup resource does not have any label, the script and migration go fine.

[controller] Fix the migration_script bug with none LVMVolumeGroups labels

---

hooks/convert_bd_names_to_selector.py

There can be situation while LvmVolumeGroup migration when labels is missing, so hook will be failed
This PR fixes this situation.
Working migration hook.

[internal] Fix possible labels miss

---

api/LICENSE

Adding LICENSE file
It will enable us using https://pkg.go.dev/license-policy
License is present and we are able to see published symbols there: https://pkg.go.dev/github.com/deckhouse/sds-node-configurator/api/v1alpha1

[docs] Add license to api module

---

crds/blockdevices.yaml
crds/lvmlogicalvolume.yaml
crds/lvmvolumegroup.yaml
crds/lvmvolumegroupbackup.yaml
crds/lvmvolumegroupset.yaml
images/agent/src/go.mod
images/sds-health-watcher-controller/src/go.mod

We need to backup our CRs
Our internal backup mechanism needs label on CRD to recognize it
Correct backup work

[internal] Add backup control label

---

images/agent/src/internal/controller/bd/discoverer.go

This PR limits the length of label values for `BlockDevice` resources to 63 symbols. If a label value exceeds this limit, it is truncated to comply with Kubernetes restrictions, as Kubernetes does not allow label values longer than 63 characters.
Kubernetes enforces a strict 63-character limit for label values. Without this change, `BlockDevice` resources with label values exceeding this limit could cause errors during resource creation or updates. By truncating values, this fix ensures compliance and prevents such errors.
- Label values for `BlockDevice` resources are truncated to 63 characters if they exceed the limit.
- Successful creation and management of `BlockDevice` resources, even when original label values are longer than 63 characters.

[controller] Limit the length of label values for `BlockDevice` resources to 63 symbols

---

images/agent/src/go.mod
images/sds-health-watcher-controller/src/go.mod

Developing in two separate go modules simultaneously requires this step to be done after the merge has happened in the base package
This fixes CI step failure
Build step to become green

[ci] Update snc api package versions in images

---

hooks/convert_bd_names_to_selector.py

Fixes `convert_bd_names_to_selector.py` to handle LVGs without finalizers.
Link to backport to [v0.4](https://github.com/deckhouse/sds-node-configurator/pull/109).
Client upgrading from <=0.2.3 to >=0.4.0 may see errors in `convert_bd_names_to_selector.py` related to LVG finalizers being empty. After the current change, script will handle this case properly and add the default finalizer, if it doesn't exist.
- clients with errors will update to current fix and see errors are gone
- LVGs without the default finalizer will have one after the migration

[internal] Fix access to missing finalizers, always add default finalizer

---

hooks/convert_bd_names_to_selector.py

This is backport of the fix to v0.4 branch.
Fixes `convert_bd_names_to_selector.py` to handle LVGs without finalizers.
Client upgrading from <=0.2.3 to >=0.4.0 may see errors in `convert_bd_names_to_selector.py` related to LVG finalizers being empty. After the current change, script will handle this case properly and add the default finalizer, if it doesn't exist.
- clients with errors will update to current fix and see errors are gone
- LVGs without the default finalizer will have one after the migration

[internal] Backport: Fix access to missing finalizers, always add default finalizer

---

openapi/config-values.yaml
templates/agent/daemonset.yaml

When the snapshot-controller is enabled and thin pools are in use, the dm_snapshot module should be loaded automatically.
Correct work with volume snapshots

[controller] Add dm_snapshot loading 

---

.gitignore
docs/FAQ.md
docs/FAQ_RU.md

Add labels list for BlockDevice in docs
Correct documentation

[docs] Add labels list for BlockDevice

---

.github/workflows/build_dev.yml
images/agent/src/go.mod
images/agent/werf.inc.yaml
images/sds-health-watcher-controller/src/go.mod
images/sds-health-watcher-controller/src/pkg/kubutils/kubernetes.go
images/sds-health-watcher-controller/werf.inc.yaml
images/sds-utils-installer/werf.inc.yaml

Migration from ALT P10 to ALT P11
ALT P10 is becoming outdated soon. We need to update the image version.

[internal] Migrate to ALT P11
